version: '3.7'

services:
  main:
    image: node:16
    environment:
      ENVIRONMENT: stage
      LOG_LEVEL: debug
      PORT: 3000
      MONGO_URI: mongodb://root:example@mongo:27017/
      REDIS_URI: redis:6379
      DATABASE_NAME: notifications
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    working_dir: /code
    ports: [ '3000:3000', '9229:9229' ]
    command: 'npm run start:dev'
    depends_on: [ redis ]
    env_file:
      - .env
  
  redis:
    image: redis:6-alpine
    ports: 
      - '6379:6379'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/mongodb:/data/db
    ports:
     - "27017:27017"

